basePath: /api/v1
definitions:
  internal_delivery_http_handlers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_delivery_http_handlers.PostResponse:
    properties:
      content:
        type: string
      cover_image_url:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      published_at:
        type: string
      slug:
        type: string
      status:
        type: string
      summary:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Personal dev platform API
  title: Devfolio API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_delivery_http_handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Admin login
      tags:
      - auth
  /health:
    get:
      description: Check API status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health
  /posts:
    get:
      description: Get list of published posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_delivery_http_handlers.PostResponse'
            type: array
      summary: List published posts
      tags:
      - posts
  /posts/{slug}:
    get:
      description: Get single post detail
      parameters:
      - description: Post slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_delivery_http_handlers.PostResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get post by slug
      tags:
      - posts
swagger: "2.0"
